# Generated by Django 4.2.11 on 2024-12-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField(max_length=500)),
                ('ingredients', models.ManyToManyField(to='ingredients.ingredient')),
            ],
        ),
    ]
