name: Django CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Start Services with Docker Compose
      run: |
        docker compose up -d --build

    - name: Run Tests
      run: |
        docker compose exec web python manage.py test
